import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import { dark } from "@clerk/themes";
import { RouteBroadcaster } from "./routeBroadcaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
  appearance={{
  theme: dark,
    elements: {
    formButtonPrimary: {
      backgroundColor: "#00a86b",
      border: "none",
      boxShadow: "none",

      "&:hover": {
        backgroundColor: "#01BF90", 
      },
    },

    footerActionLink: {
      color: "#00a86b", 

      "&:hover": {
        color: "#01BF90",
      },
    },
  },

}}
>
       
          <RouteBroadcaster />
          {children}
          <Toaster position="top-right" richColors />
        </ClerkProvider>
      </body>
    </html>
  );
}